### ISSUE TITLE
[BUG] Getting Started MovieLens TF training notebook throws cudaErrorIllegalAddress

### ISSUE THREAD

**Issue by georgeliu95** [NVIDIA/NVTabular#816]
**Describe the bug**
cudaErrorIllegalAddress occurs when running [this line](https://github.com/NVIDIA/NVTabular/blob/main/examples/getting-started-movielens/03-Training-with-TF.ipynb?short_path=f2a24bb#L310) in getting-started-movielens example.
```python
batch = next(iter(train_dataset_tf))
```

**Steps/Code to reproduce bug**
Run getting-started-movielens/03-Training-with-TF.ipynb in a [Merlin Tensorflow Training container](https://ngc.nvidia.com/catalog/containers/nvidia:merlin:merlin-tensorflow-training).

**Expected behavior**
The example should be run without errors.

**Environment details (please complete the following information):**
 - Environment location: [Docker: nvcr.io/nvidia/merlin/merlin-tensorflow-training:0.5.1]
 - Method of NVTabular install: [Docker]
   - If method of install is [Docker], provide `docker pull` & `docker run` commands used
   - docker run command: 
```shell
NV_GPU=1,3 nvidia-docker run --rm -it -p 8888:8888 -p 8797:8787 -p 8796:8786 --ipc=host nvcr.io/nvidia/merlin/merlin-tensorflow-training:0.5.1 /bin/bash`
```

**Additional context**

```shell
2021-05-17 13:38:40.032848: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1287] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-05-17 13:38:40.032956: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1293]      0 1
2021-05-17 13:38:40.032974: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1306] 0:   N N
2021-05-17 13:38:40.032997: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1306] 1:   N N
2021-05-17 13:38:40.039002: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10576 MB memory) -> physical GPU (device: 0, name: Tesla T4, pci bus id: 0000:02:00.0, compute capability: 7.5)
2021-05-17 13:38:40.040737: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 13549 MB memory) -> physical GPU (device: 1, name: Tesla T4, pci bus id: 0000:84:00.0, compute capability: 7.5)
2021-05-17 13:38:41.046167: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 10.33G (11089739776 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2021-05-17 13:38:41.048497: I tensorflow/stream_executor/cuda/cuda_driver.cc:789] failed to allocate 9.29G (9980765184 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  transform: failed to synchronize: cudaErrorIllegalAddress: an illegal memory access was encountered
```

**Comment by karlhigley** [comment]
It looks like this is due to failing to allocate memory on the device. I've run into this issue (or something similar) when I run the example notebooks in sequence on smaller GPUs (~11GB), since the 2nd MovieLens notebook doesn't automatically release the GPU memory it allocates. Stopping the kernel for the second notebook to release the memory before running the training notebook has worked for me, so that might be an acceptable workaround, but it does seem like it should be possible to run the example notebooks straight through without manual interventions to free up memory.

**Comment by georgeliu95** [comment]
Thank you Karl @karlhigley.
